controllers/SiteController.php
<?php
namespace app\controllers;
use app\models\ContactForm;
use app\models\Log;
use app\models\LoginForm;
use app\models\Order;
use app\models\OrderSearch;
use Yii;
use yii\bootstrap\Html;
use yii\db\Expression;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\UploadedFile;
class SiteController extends Controller {
	/**
	 * {@inheritdoc}
	 */
	public function behaviors() {
		return [
			'access'  => [
				'class' => AccessControl::className(),//AccessControl::className(),
				'only' => ['login', 'error', 'logout', 'index', 'view', 'upload'],
				'rules' => [
					[
						'actions' => [ 'login', 'error' ],
						'allow'   => true,
					],
					[
						'actions' => [ 'logout', 'index', 'view', 'upload' ], // add all actions to take guest to login page
						'allow'   => true,
						'roles'   => [ '@' ],
					],
				],
			],
		];
	}
	/**
	 * {@inheritdoc}
	 */
	public function actions() {
		return [
			'error'   => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class'           => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
//			'auth' => [
//				'class'           => 'yii\authclient\AuthAction',
//				'successCallback' => [ $this, 'successCallback' ],
//				'successUrl'      => $this->successUrl
//			],
		];
	}
	/**
	 * Displays homepage.
	 *
	 * @return string
	 */
	public function actionIndex() {
		$searchModel = new OrderSearch();
		$log         = Log::find()->orderBy( 'created_at DESC' )->one();

		if ( count( Yii::$app->request->queryParams ) > 0 ) {
			$get                 = Yii::$app->request->queryParams;
			$find['OrderSearch'] = [
				$get['query_field'] => $get['query_value']
			];
			$dataProvider        = $searchModel->search( $find );
			if ( $dataProvider->getTotalCount() == 1 ) {
				return $this->redirect( [ 'site/view', 'id' => $dataProvider->query->one()->no_faktur ] );
			}
			return $this->render( 'index', [
//				'searchModel'  => $searchModel,
				'dataProvider' => $dataProvider,
				'log'          => $log
			] );
		} else {
//			echo 'test';
//			die('1');
			return $this->render( 'index', [
//				'searchModel'  => $searchModel,
				'dataProvider' => null,
				'log'          => $log
			] );
		}
	}
	/**
	 * Displays homepage.
	 *
	 * @return string
	 * @throws \yii\db\Exception
	 */
	public function actionUpload() {
		if ( Yii::$app->request->post() ) {
			set_time_limit(0);
			$image   = UploadedFile::getInstanceByName( '_data_' );
			$dirName = Yii::getAlias( '@runtime' );
			$flname  = tempnam( $dirName, '_data_' );
			$image->saveAs( $flname );
//		    $uploadPath = $flname;
//		    $namafile = $post['biodata_id'] . ".jpg";
			$_data_ = file( $flname );
			$key    = [
				'no_faktur',
				'tgl',
				'kd_mhn',
				'nm_mhn',
				'almt_mhn',
				'ds_mhn',
				'kec_mhn',
				'kab_mhn',
				'kdpos_mhn',
				'noktp_mhn',
				'telp_mhn',
				'kd_cust',
				'nm_cust',
				'almt_cust',
				'ds_cust',
				'kec_cust',
				'kab_cust',
				'kdpos_cust',
				'noktp_cust',
				'telp_cust',
				'no_mesin',
				'no_rangka',
				'warna',
				'warna_list',
				'nm_mtr',
				'type_mtr',
				'tahun',
				'hrg',
				'um',
				'tenor',
				'cicilan',
				'kd_bayar',
				'no_pol',
				'stnk_jadi',
				'stnk_ambil',
				'tgl_stnk',
				'notis_jadi',
				'plat_jadi',
				'plat_ambil',
				'bpkb_jadi',
				'bpkb_ambil',
				'no_bpkb',
				'tgl_bpkb',
				'no_stck',
				'tgl_stck',
				'nm_cmo',
				'nm_sales',
				'nm_admin'
			];
			$hasil  = [];
			foreach ( $_data_ as $line ) {
				$value = explode( '#', $line );
//				$attrib = [];
				$order = Order::find()->where( [
					'no_faktur' => $value[0]
				] )->one();
				if ( $order == null ) {
					$order = new Order();
				}
				for ( $i = 0; $i < count( $key ); $i ++ ) {
					$order->setAttribute( $key[ $i ], $value[ $i ] );
				}
				if ( $order->save() ) {
					$hasil[ $order->no_faktur ] = '<p class="text-success">Berhasil diupload</p>';
					$log                        = new Log;
					$command                    = Yii::$app->getDb()
					                                       ->createCommand( "SELECT UUID();" );
					$log->log_id                = $command->queryScalar();
					$log->no_faktur             = $order->no_faktur;
					$log->created_at            = new Expression( 'now()' );
					if ( ! $log->save() ) {
						Yii::error( print_r( $log->getErrorSummary( true ) ) );
					}
				} else {
					$hasil[ $order->no_faktur ] = '<p class="text-danger">Gagal diupload. ' . Html::errorSummary( $order ) . '</p>';
				}
			}
			return $this->render( 'hasil', [
				'hasil_upload' => $hasil
			] );
		}
		return $this->render( 'upload' );
	}
	/**
	 * Displays a single Order model.
	 *
	 * @param string $id
	 *
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionView( $id ) {
		return $this->render( 'view', [
			'model' => $this->findModel( $id ),
			'log'   => Log::find()->where( [ 'no_faktur' => $id ] )->orderBy( 'created_at DESC' )->one()
		] );
	}
	/**
	 * Login action.
	 *
	 * @return string
	 */
	public function actionLogin() {
		if ( ! Yii::$app->user->isGuest ) {
			return $this->goHome();
		}
		$model = new LoginForm();
		if ( $model->load( Yii::$app->request->post() ) && $model->login() ) {
			return $this->goBack();
		}
//		$this->layout = 'main-login';
		return $this->render( 'login', [
			'model' => $model,
		] );
	}
	/**
	 * Logout action.
	 *
	 * @return Response
	 */
	public function actionLogout() {
		Yii::$app->user->logout();
		return $this->goHome();
	}
	/**
	 * Displays contact page.
	 *
	 * @return Response|string
	 */
	public function actionContact() {
		$model = new ContactForm();
		if ( $model->load( Yii::$app->request->post() ) && $model->contact( Yii::$app->params['adminEmail'] ) ) {
			Yii::$app->session->setFlash( 'contactFormSubmitted' );
			return $this->refresh();
		}
		return $this->render( 'contact', [
			'model' => $model,
		] );
	}
	/**
	 * Displays about page.
	 *
	 * @return string
	 */
	public function actionAbout() {
		return $this->render( 'about' );
	}
	/**
	 * Finds the Order model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 *
	 * @param string $id
	 *
	 * @return Order the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel( $id ) {
		if ( ( $model = Order::findOne( $id ) ) !== null ) {
			return $model;
		}
		throw new NotFoundHttpException( Yii::t( 'app', 'The requested page does not exist.' ) );
	}
}

views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>
<section>
    <div class="widthBox">
	    <?= $content ?>
</section>
<!--<div class="siteMap">-->
<!--    <div class="widthBox">-->
<!--        <div class="panelWrapper fullBox">-->
<!--            <div class="sitemapBox fullBox">-->
<!--                <div class="panelx">-->
<!--                    <div class="box">-->
<!--                        <div class="heading">-->
<!--                            <h3>Profil</h3>-->
<!--                        </div>-->
<!--                        <ul class="list">-->
<!--                            <li><a href="" >Profile</a></li>-->
<!--                            <li><a href="" >Visi Misi</a></li>-->
<!--                            <li><a href="" >ONE HEART</a></li>-->
<!--                            <li><a href="" >Sejarah</a></li>-->
<!--                            <li><a href="" >Foto</a></li>-->
<!--                        </ul></div></div>-->
<!--                <div class="panelx">-->
<!--                    <div class="box">-->
<!--                        <div class="heading">-->
<!--                            <h3>Produk</h3>-->
<!--                        </div>-->
<!--                        <ul class="list">-->
<!--                            <li><a href="" >Honda Matik</a></li>-->
<!--                            <li><a href="" >Honda Bebek</a></li>-->
<!--                            <li><a href="" >Honda Sport</a></li>-->
<!--                            <li><a href="" >Price List</a></li>-->
<!--                        </ul></div></div>-->
<!--                <div class="panelx">-->
<!--                    <div class="box">-->
<!--                        <div class="heading">-->
<!--                            <h3>Layanan</h3>-->
<!--                        </div>-->
<!--                        <ul class="list">-->
<!--                            <li><a href="" >Penjualan</a></li>-->
<!--                            <li><a href="" >Booking Service</a></li>-->
<!--                            <li><a href="" >Service Ditempat</a></li>-->
<!--                            <li><a href="" >Service Darurat</a></li>-->
<!--                        </ul></div></div>-->
<!--                <div class="panelx">-->
<!--                    <div class="box">-->
<!--                        <div class="heading">-->
<!--                            <h3>Jam kerja</h3>-->
<!--                        </div>-->
<!--                        <ul class="list">-->
<!--                            <li><a href="" >Senin - Jum'at	08:00 - 16:30</a></li>-->
<!--                            <li><a href="" >Sabtu	08:00 - 15:00</a></li>-->
<!--                            <li><a href="" >Minggu	09:00 - 15:00</a></li>-->
<!--                        </ul></div></div>-->
<!---->
<!---->
<!--            </div>-->
<!--            <div class="customerPanel">-->
<!--                <div class="box">-->
<!--                    <div class="heading">-->
<!--                        <h3>customer care</h3>-->
<!--                    </div>-->
<!---->
<!--                    <div class="custcareCaption">-->
<!--                        <p>PD. Star Motor II <br /> Jl. A. Yani No.27, Cikampek<br /> Tel. </p>-->
<!--                    </div>-->
<!---->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<!--<footer>-->
<!--    <p>&copy; Copyright 2018, <a href="" title="">Ahass Honda Motor</a>. All Rights Reserved.</p>-->
<!--</footer>      <a href="#" class="backtopScroll"></a>-->
<!--</div>-->

views/layouts/header.php
<?php
use yii\helpers\Url;
/* @var $this \yii\web\View */
/* @var $content string */
?>
<header>
    <div class="logoWrapper">
        <div class="widthBox fullBox">
            <div class="hondaLogo">
                <a href="<?php Url::home( true ); ?>">
                    <img src="<?= Url::base(); ?>/images/rsz_favicon.png"
                         alt="Sepeda Motor Honda Terbaru by Star II"
                    >
                </a>
            </div>
            <div class="ahmLogo">
                <a href="<?= Url::home( true ); ?>">
                    <img src="<?= Url::base(); ?>/images/img_logo_honda.png" alt="Ahass">
                </a>
            </div>
        </div>
    </div>
</header>
<nav>
    <div class="widthBox fullBox">
        <a href="#!" class="mobile-brand"><img src="<?= Url::base(); ?>/images/home.png"></a>
        <div id="mobnav-btn">
            Menu<span class="fa fa-reorder"></span>
        </div>
        <div class="leftNav">
            <ul class="menu fullBox">
                <li>
                    <a href="<?= Url::home( true ); ?>">
                        <img class="imgx" src="<?= Url::base(); ?>/images/home.png">
                        <span>home</span>
                    </a>
                </li>
				<?php if ( ! Yii::$app->user->isGuest ) : ?>
                    <li>
                        <a href="<?= Url::toRoute( 'site/upload' ); ?>">
                            <span>Upload</span>
                        </a>
                    </li>
				<?php endif; ?>
                <!--                <li>-->
                <!--                    <a href="" >-->
                <!--                        <span>TENTANG KAMI</span>-->
                <!--                    </a>-->
                <!--                    <ul class="subMenu">-->
                <!--                        <li>-->
                <!--                            <a href="" >-->
                <!--                                PROFIL-->
                <!--                            </a></li>-->
                <!--                        <li>-->
                <!--                            <a href="" >-->
                <!--                                VISI MISI-->
                <!--                            </a></li>-->
                <!--                        <li>-->
                <!--                            <a href="" >-->
                <!--                                SEJARAH-->
                <!--                            </a></li>-->
                <!---->
                <!--                    </ul></li>-->
                <!--                <li>-->
                <!--                    <a href="" >-->
                <!--                        <span>PRODUK</span>-->
                <!--                    </a>-->
                <!--                </li>-->
                <!---->
                <!--                <li>-->
                <!--                    <a href="" >-->
                <!--                        <span>Cari Motor</span>-->
                <!--                    </a>-->
                <!--                </li>-->
                <!--                <li>-->
                <!--                    <a href="" >-->
                <!--                        <span>Simulasi Pembiayaan</span>-->
                <!--                    </a>-->
                <!--                </li>-->
                <!--                <li>-->
                <!--                    <a href="" >-->
                <!--                        <span>Kontak</span>-->
                <!--                    </a>-->
                <!--                </li>-->
				<?php if ( ! Yii::$app->user->isGuest ) : ?>
                    <li>
                        <a href="<?= Url::toRoute( 'site/logout' ) ?>">
                            <span>Logout</span>
                        </a>
                    </li>
				<?php endif; ?>
            </ul>
        </div>
        <!--        <div class="rightNav">-->
        <!--            <a href="javascript:void(0)" class="search">-->
        <!--                <form method="GET" action="http://www.astra-honda.com" accept-charset="UTF-8">-->
        <!--                    <input type="text" name="s" class="searchInput"><i class="fa fa-search" aria-hidden="true"></i>-->
        <!--                    <input style="display:none;" type="submit">-->
        <!--                </form>-->
        <!--            </a>-->
        <!--        </div>-->
    </div>
</nav>

views/layouts/left.php
<aside class="main-sidebar">

    <section class="sidebar">

        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="<?= $directoryAsset ?>/img/user2-160x160.jpg" class="img-circle" alt="User Image"/>
            </div>
            <div class="pull-left info">
                <p>Alexander Pierce</p>

                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
              <span class="input-group-btn">
                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>
        <!-- /.search form -->

        <?= dmstr\widgets\Menu::widget(
            [
                'options' => ['class' => 'sidebar-menu tree', 'data-widget'=> 'tree'],
                'items' => [
                    ['label' => 'Menu Yii2', 'options' => ['class' => 'header']],
                    ['label' => 'Gii', 'icon' => 'file-code-o', 'url' => ['/gii']],
                    ['label' => 'Debug', 'icon' => 'dashboard', 'url' => ['/debug']],
                    ['label' => 'Login', 'url' => ['site/login'], 'visible' => Yii::$app->user->isGuest],
                    [
                        'label' => 'Some tools',
                        'icon' => 'share',
                        'url' => '#',
                        'items' => [
                            ['label' => 'Gii', 'icon' => 'file-code-o', 'url' => ['/gii'],],
                            ['label' => 'Debug', 'icon' => 'dashboard', 'url' => ['/debug'],],
                            [
                                'label' => 'Level One',
                                'icon' => 'circle-o',
                                'url' => '#',
                                'items' => [
                                    ['label' => 'Level Two', 'icon' => 'circle-o', 'url' => '#',],
                                    [
                                        'label' => 'Level Two',
                                        'icon' => 'circle-o',
                                        'url' => '#',
                                        'items' => [
                                            ['label' => 'Level Three', 'icon' => 'circle-o', 'url' => '#',],
                                            ['label' => 'Level Three', 'icon' => 'circle-o', 'url' => '#',],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ]
        ) ?>

    </section>

</aside>

views/layouts/main-login.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */
use app\assets\AppAsset;
use app\widgets\Alert;
use yii\helpers\Html;
AppAsset::register( $this );
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
    <title><?= Html::encode( $this->title ) ?></title>
	<?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<div class="wrap">
    <div class="container">
		<?= Alert::widget() ?>
		<?= $content ?>
    </div>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
/* @var $this \yii\web\View */
/* @var $content string */
app\assets\AppAsset::register( $this );
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="<?=Url::base();?>/images/favicon.png">
    <link rel="stylesheet" id="my-font" href="http://fonts.googleapis.com/css?family=Oswald" type="text/css" media="all">

    <!--    <link rel="shortcut icon" type="image/x-icon" href="--><? //=$directoryAsset?><!--/img/favicon.png">-->
	<?= Html::csrfMetaTags() ?>
    <title><?= Html::encode( $this->title ) ?></title>
	<?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<div class="wrapper">
	<?= $this->render(
		'header.php'
//		['directoryAsset' => $directoryAsset]
	) ?>

	<?= $this->render(
		'content.php',
		[
			'content'        => $content,
//			'directoryAsset' => $directoryAsset
		]
	) ?>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>